---
- name: Mac Setup
  hosts: localhost
  connection: local
  # become: true
  tasks:
    - name: Clone ansible playbook repo
      ansible.builtin.git:
        repo: https://github.com/raganw/macbook-setup.git
        dest: "{{ansible_env.HOME}}/Developer/macbook-setup"
        clone: yes
        update: yes
      tags: install, update

    - name: Update homebrew 
      community.general.homebrew:
        state: latest
        update_homebrew: yes
      tags: install, update

    - name: Tap homebrew caskroom/cask
      community.general.homebrew_tap:
        tap: "homebrew/cask"
      tags: install, tap

    - name: Install zsh
      community.general.homebrew:
        name: zsh
        state: present
      tags: install, zsh

    - name: Change shell to zsh
      shell: chsh -s $(which zsh)
      become: true
      tags: install, sudo, zsh

    - name: Install oh-my-zsh
      shell: 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"'
      args:
        creates: "{{ansible_env.HOME}}/.oh-my-zsh"
      tags: install, zsh

    - name: Install zsh-autosuggestions
      ansible.builtin.git:
        repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
        dest: "{{ansible_env.HOME}}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
      tags: install, zsh
