---
- name: Mac Setup
  hosts: localhost
  connection: local
  # become: true
  vars_files:
    - vars/packages.yml

  pre_tasks:
    - name: Update homebrew
      community.general.homebrew:
        state: latest
        update_homebrew: true
      tags: install, update

  tasks:
    - name: Clone ansible playbook repo
      ansible.builtin.git:
        repo: https://github.com/raganw/macbook-setup.git
        version: main
        dest: "{{ ansible_env.HOME }}/Developer/macbook-setup"
        clone: true
        update: true
      tags: install, update


    - ansible.builtin.import_tasks: tasks/homebrew.yml
    - ansible.builtin.import_tasks: tasks/zsh.yml
    - ansible.builtin.import_tasks: tasks/packages.yml
