---
- name: Mac Setup
  hosts: localhost
  connection: local
  # become: true
  vars_files:
    - vars/packages.yml

  tasks:
    - name: Clone ansible playbook repo
      ansible.builtin.git:
        repo: https://github.com/raganw/macbook-setup.git
        version: main
        dest: "{{ ansible_env.HOME }}/Developer/macbook-setup"
        clone: true
        update: true
      tags: install, update


    - include: tasks/homebrew.yml
    - include: tasks/zsh.yml
    - include: tasks/packages.yml
