---
- name: Mac Setup
  hosts: all
  connection: local
  # become: true
  tasks:
    - name: Install homebrew
      shell: 'yes | /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'
      args:
        creates: /usr/local/bin/brew
      tags: install

    - name: Update homebrew 
      community.general.homebrew:
        state: latest
        update_homebrew: yes
      tags: install, update

    - name: Tap homebrew caskroom/cask
      community.general.homebrew_tap:
        tap: "homebrew/cask"
      tags: install, tap

    - name: Install zsh
      community.general.homebrew:
        name: zsh
        state: present

    - name: Install oh-my-zsh
      shell: 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"'
      args:
        creates: ${HOME}/.oh-my-zsh

